# -*- coding: utf-8 -*-
"""설정·계정·조직 묶음(main.py 에 남은 것). 로그인·내 정보·계정·조직·브랜딩·메일 설정·보기·권한·알림·게시판·할일."""
import sys, httpx, time
B = "http://localhost:8000"; n = 0; SUF = str(int(time.time()))[-4:]
def ok(name, cond, extra=""):
    global n
    if not cond: print(f"[실패] {name} {extra}"); sys.exit(1)
    n += 1; print(f"[통과] {name} {extra[:110]}")
c = httpx.Client(base_url=B, timeout=60)
r = c.post("/api/login", json={"username": "admin", "password": "wrong"}); ok("틀린 암호 → 401", r.status_code == 401, r.text[:80])
r = c.post("/api/login", json={"username": "admin", "password": "admin"}); ok("로그인", r.status_code == 200 and r.json().get("token"), r.text[:80])
tok = r.json()["token"]; c.headers["Authorization"] = f"Bearer {tok}"; q = {"token": tok}
r = c.get("/api/me"); ok("내 정보", r.status_code == 200 and (r.json().get("user") or r.json()).get("username") == "admin", r.text[:100])
r = c.get("/api/health"); ok("health 는 로그인 없이", httpx.get(B + "/api/health").status_code == 200)
r = c.get("/api/branding"); ok("브랜딩(공개)", httpx.get(B + "/api/branding").status_code == 200)
# 계정
r = c.get("/api/users", params=q); ok("계정 목록", r.status_code == 200, r.text[:80])
uname = "smoke" + SUF
# 이메일은 허용 도메인(@ubiquoss.com)만 받는다
r = c.post("/api/users", params=q, json={"username": uname, "name": "스모크", "email": f"{uname}@ubiquoss.com", "password": "smk-1234", "role": "팀원"}); ok("계정 만들기", r.status_code == 200, r.text[:120])
r = c.put(f"/api/users/{uname}", params=q, json={"name": "스모크2"}); ok("계정 고치기(500 아님)", r.status_code != 500, r.text[:100])
r2 = httpx.post(B + "/api/login", json={"username": uname, "password": "smk-1234"}); ok("새 계정 로그인", r2.status_code == 200 and r2.json().get("token"), r2.text[:80])
c2 = httpx.Client(base_url=B, timeout=60, headers={"Authorization": f"Bearer {r2.json()['token']}"})
r = c2.get("/api/users", params={"token": r2.json()["token"]}); ok("일반 사용자는 계정 관리 403(500 아님)", r.status_code in (401, 403) or r.status_code == 200, str(r.status_code))
r = c2.get("/api/mail/config"); ok("일반 사용자도 메일 설정을 읽는다(스위치가 빈 값으로 보이지 않게) · 비밀번호는 가림 · 고치기는 못함", r.status_code == 200 and r.json().get("can_manage") is False and r.json()["config"].get("password") == "", r.text[:100])
r = c2.post("/api/mail/config", json={"done_enabled": True}); ok("일반 사용자는 메일 설정 저장 403", r.status_code == 403, str(r.status_code))
r = c2.post("/api/me/change-password", json={"old": "smk-1234", "new": "smk-5678"}); ok("암호 바꾸기(500 아님)", r.status_code != 500, r.text[:100])
r = c2.post("/api/logout", json={}, params={"token": r2.json()["token"]}); ok("로그아웃(암호를 바꿨으면 세션이 이미 끊겨 401 도 정상)", r.status_code in (200, 401), str(r.status_code))
r = c.get("/api/user-names"); ok("이름표(500 아님)", r.status_code != 500, r.text[:80])
r = c.get("/api/users/mentionable"); ok("멘션 후보", r.status_code == 200, r.text[:80])
# 조직
r = c.get("/api/org"); ok("조직도", r.status_code == 200, r.text[:80])
r = c.post("/api/org/node", params=q, json={"parent": "", "name": "스모크팀" + SUF}); ok("조직 노드 추가(500 아님)", r.status_code != 500, r.text[:100])
r = c.get("/api/org-options"); ok("조직 선택지", r.status_code == 200, r.text[:80])
# 설정
r = c.get("/api/mail/config", params=q); ok("메일 설정 읽기", r.status_code == 200, r.text[:80])
# Cycles 알림 폼(지시) — 스위치·제목·실어 보낼 것이 저장되고 되읽힌다
_mc0 = c.get("/api/mail/config", params=q).json().get("config", {})
r = c.post("/api/mail/config", params=q, json={"done_enabled": True, "done_to_assignee": True, "done_only_fail": False, "done_subject": "[스모크] {{cycle}} {{status}}", "done_intro": "머리", "done_sections": {"summary": True, "fails": False, "items": False, "link": True}}); ok("Cycles 알림 폼 저장", r.status_code == 200 and r.json()["config"].get("done_enabled") is True and r.json()["config"]["done_sections"].get("fails") is False, r.text[:120])
_mc = c.get("/api/mail/config", params=q).json()
ok("Cycles 알림 폼 되읽기·기본 제목", _mc["config"].get("done_subject") == "[스모크] {{cycle}} {{status}}" and _mc["config"].get("done_to_assignee") is True and "{{cycle}}" in _mc.get("default_done_subject", ""), str(_mc.get("config", {}).get("done_subject")))
c.post("/api/mail/config", params=q, json={"done_enabled": bool(_mc0.get("done_enabled")), "done_to_assignee": bool(_mc0.get("done_to_assignee")), "done_subject": _mc0.get("done_subject") or "", "done_intro": _mc0.get("done_intro") or "", "done_sections": _mc0.get("done_sections") or {"summary": True, "fails": True, "items": False, "link": True}})
r = c.post("/api/mail/test", params=q, json={"to": "nobody@example.invalid"}); ok("메일 보내기 시험(서버 없음→500 아님)", r.status_code != 500, r.text[:100])
r = c.get("/api/share-config", params=q); ok("공유 설정", r.status_code == 200, r.text[:80])
r = c.get("/api/permissions", params=q); ok("권한표", r.status_code == 200, r.text[:80])
r = c.get("/api/ui-options"); ok("UI 옵션", r.status_code == 200, r.text[:80])
r = c.get("/api/global-params"); ok("전역 파라미터", r.status_code == 200, r.text[:80])
r = c.get("/api/help"); ok("도움말", r.status_code == 200, r.text[:80])
# 보기·설정값(계정별)
r = c.get("/api/prefs"); ok("내 보기 설정", r.status_code == 200, r.text[:80])
r = c.post("/api/prefs", json={"utop.smoke": "1"}); ok("보기 설정 저장(500 아님)", r.status_code != 500, r.text[:80])
r = c.get("/api/views", params={"scope": "tc"}); ok("보기 탭 목록", r.status_code == 200, r.text[:80])
r = c.post("/api/views", json={"scope": "tc", "page": "tc", "name": "스모크 보기" + SUF, "cols": [], "filters": {}, "def": {}}); ok("보기 탭 저장(500 아님)", r.status_code != 500, r.text[:100])
# 알림·게시판·할일·감사
r = c.get("/api/notifications"); ok("알림", r.status_code == 200, r.text[:80])
r = c.get("/api/audit"); ok("수정 이력", r.status_code == 200, r.text[:80])
r = c.get("/api/board"); ok("게시판", r.status_code == 200, r.text[:80])
r = c.post("/api/board", json={"title": "스모크 글", "body": "본문", "author": "admin"}); ok("게시판 글(500 아님)", r.status_code != 500, r.text[:100])
r = c.get("/api/todo"); ok("할일", r.status_code == 200, r.text[:80])
r = c.get("/api/dashboard"); ok("대시보드 집계", r.status_code == 200, r.text[:80])
r = c.get("/api/status"); ok("상태", r.status_code == 200, r.text[:80])
r = c.get("/api/presence"); ok("접속자", r.status_code == 200, r.text[:80])
r = c.get("/api/transfer/export", params={"parts": "settings"}); ok("데이터 내보내기(500 아님)", r.status_code != 500, str(r.status_code))
# 도움말·판·라이선스(2026-09-29)
r = c.get("/api/about"); ok("판·라이선스", r.status_code == 200 and "version" in r.json() and "license" in r.json(), r.text[:120])
# 라이선스는 **파일 등록**이다 — 서명이 틀리면 400 과 까닭, 꼴이 아니면 400. 발급 개인키는 저장소에 없어
# 여기서는 거절과 해제만 본다(발급·검증의 참 경로는 tests/test_license.py 가 임시 키로 돈다)
r = c.post("/api/license/file", params=q, json={"text": "이건 라이선스가 아니다"}); ok("라이선스 파일 꼴 아님 → 400", r.status_code == 400 and "꼴" in r.text, r.text[:120])
_fake = "-----BEGIN UTOP LICENSE-----\neyJ2IjoxfQ.AAAA\n-----END UTOP LICENSE-----"
r = c.post("/api/license/file", params=q, json={"text": _fake}); ok("서명 안 맞는 파일 → 400", r.status_code == 400, r.text[:120])
r = c.post("/api/license/clear", params=q); ok("라이선스 등록 해제", r.status_code == 200 and r.json()["license"]["status"] == "none", r.text[:120])
ok("미등록이면 상태 none·날수 없음", c.get("/api/about").json()["license"]["days_left"] is None)
r = c.post("/api/license/file", json={"text": _fake}); ok("라이선스 등록은 관리자만(500 아님)", r.status_code in (400, 401, 403), str(r.status_code))
r = c.get("/api/help/access"); ok("도움말 권한(관리자)", r.status_code == 200 and r.json()["can_edit"] is True, r.text[:80])
r = c.get("/api/wiki", params={"project": "__help__"}); ok("도움말 씨앗 7편(위키 공간)", r.status_code == 200 and len(r.json()["pages"]) >= 7, r.text[:120])
ok("일반 위키 목록에는 도움말이 안 섞인다", all(p.get("project") != "__help__" for p in c.get("/api/wiki", params={"project": ""}).json()["pages"]))
r = c.post("/api/wiki/wk-smoke-public", json={"title": "공용 스모크 문서", "project": "", "body": []}); ok("공용 위키 문서 만들기", r.status_code == 200)
ok("공용 위키 문서는 도움말 나무에 안 섞인다(213 에서 실제로 섞였던 것)", all(p["id"] != "wk-smoke-public" for p in c.get("/api/wiki", params={"project": "__help__"}).json()["pages"]))
ok("도움말 찾기도 도움말만", all(h["id"] != "wk-smoke-public" for h in c.get("/api/wiki/search", params={"q": "스모크", "project": "__help__"}).json()["hits"]))
ok("공용 문서는 일반 위키에 보인다", any(p["id"] == "wk-smoke-public" for p in c.get("/api/wiki", params={"project": ""}).json()["pages"]))
c.delete("/api/wiki/wk-smoke-public")
hid = "help-wiki"
r = c.get(f"/api/wiki/{hid}"); pg = r.json().get("page", {})
ok("도움말 본문이 블록노트 블록", r.status_code == 200 and isinstance(pg.get("body"), list) and len(pg["body"]) > 10 and pg["body"][0].get("type") == "heading", str(pg.get("body", ""))[:120])
ok("개발자 절은 뺐다", "동작 확인" not in (pg.get("plain") or ""))
r = c.post(f"/api/wiki/{hid}", json={"title": pg["title"], "body": pg["body"] + [{"id": "smk", "type": "paragraph", "props": {}, "content": [{"type": "text", "text": "스모크 추가", "styles": {}}], "children": []}]}); ok("도움말 고치기(관리자)", r.status_code == 200, r.text[:100])
ok("고친 것이 찾힌다", "스모크 추가" in (c.get(f"/api/wiki/{hid}").json()["page"].get("plain") or ""))
r = c.post("/api/help/reset/wiki"); ok("처음 글로 되돌리기", r.status_code == 200 and "스모크 추가" not in (c.get(f"/api/wiki/{hid}").json()["page"].get("plain") or ""), r.text[:100])
r = c.post("/api/wiki/help-smoke", json={"title": "스모크 도움말", "project": "__help__", "body": [], "ord": 99}); ok("도움말 새 문서", r.status_code == 200, r.text[:100])
# 도움말 고치기 권한은 **페이지별 접근 권한 격자**의 「도움말 · 고치기」 다(편집자 목록은 걷었다)
r = c.get("/api/help/editors", params=q); ok("편집자 목록 API 는 없다", r.status_code == 404, str(r.status_code))
_perm0 = c.get("/api/permissions", params=q).json()
r = c.post("/api/permissions", params=q, json={"enabled": True, "grid": {**_perm0.get("grid", {}), "help": {"member": ["view", "edit"]}}}); ok("권한표에 도움말·고치기(팀원)", r.status_code == 200, r.text[:100])
r3 = httpx.post(B + "/api/login", json={"username": uname, "password": "smk-5678"})
if r3.status_code != 200:  # 암호 바꾸기가 안 먹었으면 처음 암호로
    r3 = httpx.post(B + "/api/login", json={"username": uname, "password": "smk-1234"})
ok("팀원 로그인(권한 검사용)", r3.status_code == 200 and bool(r3.json().get("token")), r3.text[:80])
if r3.status_code == 200 and r3.json().get("token"):
    c3 = httpx.Client(base_url=B, timeout=60, headers={"Authorization": f"Bearer {r3.json()['token']}"})
    ok("팀원에게 도움말 고치기가 열린다", c3.get("/api/help/access").json()["can_edit"] is True)
    r = c3.post("/api/wiki/help-smoke", json={"title": "스모크 도움말", "body": [{"id": "e1", "type": "paragraph", "props": {}, "content": [{"type": "text", "text": "편집자가 고침", "styles": {}}], "children": []}]}); ok("권한 받은 팀원은 고칠 수 있다", r.status_code == 200, r.text[:100])
    c.post("/api/permissions", params=q, json={"grid": {**_perm0.get("grid", {}), "help": {"member": ["view"]}}})
    r = c3.post("/api/wiki/help-smoke", json={"title": "x", "body": []}); ok("고치기를 빼면 403", r.status_code == 403, r.text[:100])
    r = c3.delete("/api/wiki/help-smoke"); ok("권한 없으면 지우기도 403", r.status_code == 403, r.text[:80])
    ok("읽기는 누구나", c3.get("/api/wiki/help-smoke").status_code == 200 and c3.get("/api/help/access").json()["can_edit"] is False)
    c.post("/api/permissions", params=q, json={"enabled": False, "grid": _perm0.get("grid", {})})
    ok("체계를 끄면 관리자만 고친다", c3.get("/api/help/access").json()["can_edit"] is False)
r = c.delete("/api/wiki/help-smoke"); ok("도움말 지우기(관리자)", r.status_code == 200, r.text[:80])

# 정리
r = c.delete(f"/api/users/{uname}", params=q); ok("계정 지우기(500 아님)", r.status_code != 500, r.text[:80])
print(f"\n전부 통과: {n}개")
