import {
  IconAlignLeft,
  IconArrowBarToLeft,
  IconArrowBarToDown,
  IconArrowBarToRight,
  IconArrowBarToUp,
  IconArrowsSort,
  IconCalendar,
  IconCalendarPlus,
  IconCalendarWeek,
  IconChartBar,
  IconChartDonut,
  IconChartLine,
  IconCheck,
  IconCheckbox,
  IconChevronDown,
  IconChevronRight,
  IconCircleChevronDown,
  IconCircleDot,
  IconClockHour4,
  IconColumnInsertRight,
  IconColumns,
  IconCopy,
  IconCopyPlus,
  IconDownload,
  IconEraser,
  IconEye,
  IconEyeOff,
  IconFilter,
  IconFilterOff,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconGripVertical,
  IconHash,
  IconLayoutKanban,
  IconLayoutList,
  IconLayoutRows,
  IconLink,
  IconMail,
  IconMathFunction,
  IconPencil,
  IconPhone,
  IconPlus,
  IconRefresh,
  IconSquare,
  IconSortAscending,
  IconSortDescending,
  IconSum,
  IconTable,
  IconTablePlus,
  IconTags,
  IconTimeline,
  IconTrash,
  IconUpload,
  IconUser,
  IconX,
  type Icon,
} from '@tabler/icons-react'

/**
 * Effort Plan 아이콘 — 예전 화면이 쓰던 Tabler 아이콘(ti ti-*)과 같은 그림(지시: 예전과 같게).
 * 이름은 예전 클래스의 ti- 뒤 글자 그대로 쓴다 — 예전 코드와 한눈에 대조되게.
 * 쓰는 것만 가져와 앱에 묶는다(인터넷이 안 되는 서버에서도 보인다).
 */
const MAP: Record<string, Icon> = {
  'align-left': IconAlignLeft,
  'arrow-bar-to-left': IconArrowBarToLeft,
  'arrow-bar-to-down': IconArrowBarToDown,
  'arrow-bar-to-right': IconArrowBarToRight,
  'arrow-bar-to-up': IconArrowBarToUp,
  'arrows-sort': IconArrowsSort,
  calendar: IconCalendar,
  'calendar-plus': IconCalendarPlus,
  'calendar-week': IconCalendarWeek,
  'chart-bar': IconChartBar,
  'chart-donut': IconChartDonut,
  'chart-line': IconChartLine,
  check: IconCheck,
  checkbox: IconCheckbox,
  'chevron-down': IconChevronDown,
  'chevron-right': IconChevronRight,
  'circle-chevron-down': IconCircleChevronDown,
  'circle-dot': IconCircleDot,
  'clock-hour-4': IconClockHour4,
  'column-insert-right': IconColumnInsertRight,
  columns: IconColumns,
  copy: IconCopy,
  'copy-plus': IconCopyPlus,
  download: IconDownload,
  eraser: IconEraser,
  eye: IconEye,
  'eye-off': IconEyeOff,
  filter: IconFilter,
  'filter-off': IconFilterOff,
  folder: IconFolder,
  'folder-open': IconFolderOpen,
  'folder-plus': IconFolderPlus,
  grip: IconGripVertical,
  hash: IconHash,
  'layout-kanban': IconLayoutKanban,
  'layout-list': IconLayoutList,
  'layout-rows': IconLayoutRows,
  link: IconLink,
  mail: IconMail,
  'math-function': IconMathFunction,
  pencil: IconPencil,
  phone: IconPhone,
  plus: IconPlus,
  refresh: IconRefresh,
  'sort-ascending': IconSortAscending,
  'sort-descending': IconSortDescending,
  square: IconSquare,
  sum: IconSum,
  table: IconTable,
  'table-plus': IconTablePlus,
  tags: IconTags,
  timeline: IconTimeline,
  trash: IconTrash,
  upload: IconUpload,
  user: IconUser,
  x: IconX,
}

/** 예전 `<i class="ti ti-이름">` 자리 — 크기는 글자 크기(1em)를 따른다 */
export function TI({ n, className }: { n: string; className?: string }) {
  const C = MAP[n] ?? IconAlignLeft
  return <C className={`ef-ti${className ? ' ' + className : ''}`} size="1em" stroke={2} aria-hidden="true" />
}
